# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='\u4efb\u52a1\u6807\u9898'),
        ),
    ]
