# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_node_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_detail',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u98ce\u683c'),
        ),
    ]
