# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_node_detail_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_detail',
            name='is_open',
            field=models.SmallIntegerField(default=0, verbose_name='\u5f00\u5173'),
        ),
    ]
