# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_node_detail_open_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node_detail',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='node_detail',
            name='open_memo',
        ),
        migrations.AddField(
            model_name='channel',
            name='is_open',
            field=models.SmallIntegerField(default=0, verbose_name='\u5f00\u5173'),
        ),
        migrations.AddField(
            model_name='channel',
            name='open_memo',
            field=models.CharField(default='\u5173', max_length=3, verbose_name='\u5f00\u5173\u63cf\u8ff0'),
        ),
    ]
