# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20160817_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='channel',
            field=models.CharField(max_length=50, verbose_name='\u9891\u9053\u53f7'),
        ),
    ]
