# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20160819_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u9891\u9053\u7f16\u53f7')),
                ('channel', models.CharField(max_length=50, unique=True, verbose_name='\u9891\u9053\u53f7')),
                ('signal', models.CharField(max_length=50, verbose_name='\u4fe1\u53f7\u6e90')),
                ('channel_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u63cf\u8ff0')),
                ('url', models.CharField(max_length=50, verbose_name='\u76f8\u5173URL')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u9891\u9053',
            },
        ),
    ]
