# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u98ce\u683c'),
        ),
    ]
