# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_node_detail_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_detail',
            name='open_memo',
            field=models.CharField(default='\u5173', max_length=3, verbose_name='\u5f00\u5173\u63cf\u8ff0'),
        ),
    ]
