# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'\xe8\xa7\xa6\xe5\x8f\x91\xe6\x96\xb9\xe5\xbc\x8f')),
                ('conditions', models.TextField(verbose_name=b'\xe5\x91\x8a\xe8\xad\xa6\xe6\x9d\xa1\xe4\xbb\xb6')),
                ('interval', models.IntegerField(verbose_name=b'\xe8\xbd\xae\xe5\xbe\xaa\xe6\x97\xb6\xe9\x97\xb4')),
                ('enabled', models.BooleanField(default=True, verbose_name=b'\xe5\x91\x8a\xe8\xad\xa6\xe6\x98\xaf\xe5\x90\xa6\xe5\x90\xaf\xe7\x94\xa8')),
                ('subject', models.CharField(max_length=64, verbose_name=b'\xe5\x91\x8a\xe8\xad\xa6\xe4\xb8\xbb\xe9\xa2\x98')),
                ('message', models.CharField(max_length=640, verbose_name=b'\xe5\x91\x8a\xe8\xad\xa6\xe6\xb6\x88\xe6\x81\xaf')),
                ('recover_enabled', models.BooleanField(default=True, verbose_name=b'\xe6\x81\xa2\xe5\xa4\x8d\xe5\x90\x8e\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\x91\xe9\x80\x81\xe9\x80\x9a\xe7\x9f\xa5')),
                ('recover_subject', models.CharField(max_length=64, verbose_name=b'\xe6\x81\xa2\xe5\xa4\x8d\xe4\xb8\xbb\xe9\xa2\x98')),
                ('recover_message', models.CharField(max_length=640, verbose_name=b'\xe6\x81\xa2\xe5\xa4\x8d\xe5\x88\xb0\xe6\xb6\x88\xe6\x81\xaf')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u544a\u8b66\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='Action_method',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=64, verbose_name=b'\xe6\x89\xa7\xe8\xa1\x8c\xe5\x90\x8d\xe7\xa7\xb0')),
                ('step', models.SmallIntegerField(default=1, verbose_name=b'\xe7\xac\xacN\xe6\xac\xa1\xe5\x91\x8a\xe8\xad\xa6')),
                ('action_type', models.CharField(choices=[(b'email', b'Email'), (b'sms', b'SMS'), (b'script', b'RunScript')], max_length=10, verbose_name=b'\xe5\x91\x8a\xe8\xad\xa6\xe5\x8f\x91\xe9\x80\x81\xe6\x96\xb9\xe5\xbc\x8f')),
                ('notifiers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe9\x80\x9a\xe7\x9f\xa5\xe5\xaf\xb9\xe8\xb1\xa1')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u544a\u8b66\u65b9\u5f0f',
            },
        ),
        migrations.CreateModel(
            name='FlowCar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('project_id', models.SmallIntegerField(verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe7\xbc\x96\xe5\x8f\xb7')),
                ('project', models.CharField(max_length=50, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae')),
                ('operator', models.CharField(max_length=50, verbose_name=b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86')),
                ('region', models.CharField(max_length=50, verbose_name=b'\xe5\x9c\xb0\xe5\x8c\xba')),
                ('memo', models.CharField(max_length=50, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('contract', models.CharField(max_length=50, verbose_name=b'\xe5\x90\x88\xe5\x90\x8c\xe5\x8f\xb7')),
                ('basic', models.FloatField(default=0, verbose_name=b'\xe4\xbf\x9d\xe5\xba\x95\xe5\x8d\x95\xe4\xbb\xb7')),
                ('surplus', models.FloatField(default=0, verbose_name=b'\xe8\xb6\x85\xe9\x87\x8f\xe5\x8d\x95\xe4\xbb\xb7')),
                ('cabinet', models.FloatField(default=0, verbose_name=b'\xe6\x9c\xba\xe4\xbd\x8d\xe8\xb4\xb9\xe7\x94\xa8')),
                ('ip_fee', models.FloatField(default=0, verbose_name=b'IP\xe8\xb4\xb9\xe7\x94\xa8')),
                ('fees', models.CharField(default=b'basic+surplus*n+cabinet+ip_fee', max_length=50, verbose_name=b'\xe8\xae\xa1\xe8\xb4\xb9\xe6\x96\xb9\xe5\xbc\x8f')),
            ],
            options={
                'ordering': ['-project_id'],
                'verbose_name_plural': '\u5bbd\u5e26\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='FlowCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('month', models.IntegerField(verbose_name=b'\xe5\xb9\xb4\xe6\x9c\x88')),
                ('surplus', models.FloatField(default=0, verbose_name=b'\xe5\xbd\x93\xe6\x9c\x88\xe8\xb6\x85\xe9\x87\x8f\xe5\x80\xbc')),
                ('predict', models.CharField(max_length=50, verbose_name=b'\xe9\xa2\x84\xe8\xae\xa1\xe8\xb4\xb9\xe7\x94\xa8')),
                ('count', models.CharField(max_length=50, verbose_name=b'\xe8\xae\xa1\xe8\xb4\xb9\xe9\x87\x91\xe9\xa2\x9d')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u5bbd\u5e26\u8ba1\u8d39\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('his_clock', models.IntegerField(verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe8\x8e\xb7\xe5\x8f\x96\xe6\x97\xb6\xe9\x97\xb4')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\x80\xbc')),
                ('interval_time', models.IntegerField(blank=True, null=True, verbose_name=b'\xe8\xbd\xae\xe8\xaf\xa2\xe6\x97\xb6\xe9\x97\xb4')),
                ('add_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'\xe5\x8f\x98\xe5\x8c\x96\xe5\x80\xbc')),
                ('status', models.SmallIntegerField(default=0, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe7\x8a\xb6\xe6\x80\x81\xe4\xbf\xa1\xe6\x81\xaf')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u76d1\u63a7\u5386\u53f2\u6570\u636e',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('ip', models.GenericIPAddressField(verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x9c\xb0\xe5\x9d\x80')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
            ],
            options={
                'verbose_name_plural': '\u76d1\u63a7\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='Host_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe7\xbb\x84\xe7\xb1\xbb')),
            ],
            options={
                'verbose_name_plural': '\u76d1\u63a7\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(blank=True, max_length=64, unique=True, verbose_name=b'\xe6\x8c\x87\xe6\xa0\x87\xe5\x90\x8d\xe7\xa7\xb0')),
                ('key', models.CharField(max_length=64, verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe6\x9c\x8d\xe5\x8a\xa1\xe9\xa1\xb9')),
                ('last_clock', models.IntegerField(blank=True, null=True, verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe6\x9c\x80\xe5\x90\x8e\xe8\x8e\xb7\xe5\x8f\x96\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_value', models.IntegerField(blank=True, null=True, verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe6\x9c\x80\xe5\x90\x8e\xe8\x8e\xb7\xe5\x8f\x96\xe6\x95\xb0\xe6\x8d\xae')),
                ('charset', models.CharField(choices=[(b'str', b'str'), (b'int', b'int'), (b'float', b'float')], default=b'str', max_length=5, verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe8\x8e\xb7\xe5\x8f\x96\xe5\x80\xbc\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('item_type', models.CharField(choices=[(b'\xe8\x87\xaa\xe5\xbb\xbaCDN', b'\xe8\x87\xaa\xe5\xbb\xbaCDN'), (b'\xe5\x95\x86\xe7\x94\xa8CDN', b'\xe5\x95\x86\xe7\x94\xa8CDN'), (b'\xe6\xba\x90\xe8\x8a\x82\xe7\x82\xb9', b'\xe6\xba\x90\xe8\x8a\x82\xe7\x82\xb9'), (b'\xe5\x85\xb6\xe4\xbb\x96', b'\xe5\x85\xb6\xe4\xbb\x96')], default=b'\xe8\x87\xaa\xe5\xbb\xbaCDN', max_length=10, verbose_name=b'CDN\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('memo', models.CharField(max_length=64, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u76d1\u63a7\u9879',
            },
        ),
        migrations.CreateModel(
            name='Item_Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe9\xa1\xb9\xe5\x88\x86\xe7\xb1\xbb')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u76d1\u63a7\u9879\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('start_time', models.IntegerField(verbose_name=b'\xe7\xbb\xb4\xe6\x8a\xa4\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('end_time', models.IntegerField(verbose_name=b'\xe7\xbb\xb4\xe6\x8a\xa4\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('memo', models.CharField(max_length=64, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('host_groups', models.ManyToManyField(blank=True, to='monitor.Host_group', verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe7\xbb\x84')),
                ('hosts', models.ManyToManyField(blank=True, to='monitor.Host', verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u7ef4\u4fdd\u7cfb\u7edf',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=65, unique=True, verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe5\x90\x8d')),
                ('interval', models.IntegerField(default=60, verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe9\x97\xb4\xe9\x9a\x94')),
                ('plugin', models.CharField(max_length=200, verbose_name=b'\xe6\x8f\x92\xe4\xbb\xb6\xe8\x84\x9a\xe6\x9c\xac')),
                ('memo', models.CharField(max_length=64, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u76d1\u63a7\u670d\u52a1',
            },
        ),
        migrations.CreateModel(
            name='Service_Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe6\x9c\x8d\xe5\x8a\xa1\xe7\xbb\x84\xe5\x90\x8d')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u76d1\u63a7\u670d\u52a1\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xe6\xa0\x87\xe8\xaf\x86\xe5\x90\x8d')),
                ('memo', models.CharField(max_length=64, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u7279\u522b\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x90\x8d')),
                ('system', models.CharField(choices=[(b'Linux', b'Linux'), (b'Windows', b'Windows'), (b'\xe4\xba\xa4\xe6\x8d\xa2\xe6\x9c\xba', b'\xe4\xba\xa4\xe6\x8d\xa2\xe6\x9c\xba')], default=b'Linux', max_length=20)),
            ],
            options={
                'verbose_name_plural': '\u7cfb\u7edf\u540d',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name=b'\xe6\xa8\xa1\xe6\x9d\xbf\xe5\x90\x8d')),
                ('hosts', models.ManyToManyField(blank=True, to='monitor.Host', verbose_name=b'\xe5\x85\xb3\xe8\x81\x94\xe4\xb8\xbb\xe6\x9c\xba')),
                ('services', models.ManyToManyField(to='monitor.Service', verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x88\x97\xe8\xa1\xa8')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u6a21\u677f',
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=64, verbose_name=b'\xe8\xa7\xa6\xe5\x8f\x91\xe5\x99\xa8\xe5\x88\x97\xe8\xa1\xa8')),
                ('expression', models.TextField(verbose_name=b'\xe8\xa1\xa8\xe8\xbe\xbe\xe5\xbc\x8f')),
                ('severity', models.CharField(choices=[(b'info', b'info'), (b'warning', b'warning'), (b'high', b'high'), (b'critical', b'critical')], max_length=10, verbose_name=b'\xe5\x91\x8a\xe8\xad\xa6\xe7\xad\x89\xe7\xba\xa7')),
                ('enabled', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x90\xaf\xe7\x94\xa8')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u89e6\u53d1\u5668',
            },
        ),
        migrations.AddField(
            model_name='template',
            name='triggers',
            field=models.ManyToManyField(blank=True, to='monitor.Trigger', verbose_name=b'\xe8\xa7\xa6\xe5\x8f\x91\xe5\x99\xa8\xe5\x88\x97\xe8\xa1\xa8'),
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Service_Group'),
        ),
        migrations.AddField(
            model_name='service',
            name='items',
            field=models.ManyToManyField(to='monitor.Item', verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe9\xa1\xb9\xe5\x88\x97\xe8\xa1\xa8'),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Item_Group', verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe5\x88\x86\xe7\xb1\xbb'),
        ),
        migrations.AddField(
            model_name='item',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Host', verbose_name=b'\xe5\x85\xb3\xe8\x81\x94\xe4\xb8\xbb\xe6\x9c\xba'),
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='monitor.Host_group', verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe7\xbb\x84'),
        ),
        migrations.AddField(
            model_name='host',
            name='system',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='monitor.System', verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AddField(
            model_name='history',
            name='hosts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Host', verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
        migrations.AddField(
            model_name='history',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Item', verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe9\xa1\xb9'),
        ),
        migrations.AddField(
            model_name='history',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Special', verbose_name=b'\xe7\x89\xb9\xe5\x88\xab\xe6\xa0\x87\xe8\xaf\x86\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
        migrations.AddField(
            model_name='flowcount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Item', verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='flowcar',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Item', verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='action',
            name='host_groups',
            field=models.ManyToManyField(blank=True, to='monitor.Host_group', verbose_name=b'\xe8\xa7\xa6\xe5\x8f\x91\xe7\xbe\xa4\xe7\xbb\x84\xe5\x88\x97\xe8\xa1\xa8'),
        ),
        migrations.AddField(
            model_name='action',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='monitor.Host', verbose_name=b'\xe8\xa7\xa6\xe5\x8f\x91\xe4\xb8\xbb\xe6\x9c\xba\xe5\x88\x97\xe8\xa1\xa8'),
        ),
        migrations.AddField(
            model_name='action',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Trigger', verbose_name=b'\xe5\x91\x8a\xe8\xad\xa6\xe8\xa7\xa6\xe5\x8f\x91\xe5\x88\x97\xe8\xa1\xa8'),
        ),
        migrations.AddField(
            model_name='action',
            name='operations',
            field=models.ManyToManyField(to='monitor.Action_method', verbose_name=b'\xe8\xa7\xa6\xe5\x8f\x91\xe5\x91\x8a\xe8\xad\xa6\xe5\x90\x8e\xe5\x88\xb0\xe6\x96\xb9\xe5\xbc\x8f'),
        ),
    ]
