# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowcar',
            options={'ordering': ['id', '-project_id'], 'verbose_name_plural': '\u5bbd\u5e26\u5206\u7c7b'},
        ),
        migrations.AddField(
            model_name='flowcar',
            name='basic_value',
            field=models.FloatField(default=0, verbose_name=b'\xe4\xbf\x9d\xe5\xba\x95\xe5\xae\xbd\xe5\xb8\xa6'),
        ),
    ]
